name: Build and Test Qt RPS_GUI Application

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Qt and CMake dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake qtbase5-dev qtbase5-dev-tools build-essential cmake
          sudo apt-get install -y libqt5serialport5-dev  # Install Qt5 SerialPort

      ## Step 3: Build the Qt project with tests enabled
      - name: Build Qt Project with Tests
        run: |
          cd RPS_GUI  # Navigate to the project directory
          mkdir -p build
          cd build
          cmake -DBUILD_TESTS=ON ..
          make
        shell: bash

      # Step 4: Run the tests
      - name: Run Tests
        run: |
          cd RPS_GUI/build  # Ensure you're in the build directory
          ctest --output-on-failure
        shell: bash

      # Step 5: Upload test results as an artifact
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: RPS_GUI/build/tests.xml
