name: Build Qt RPS_GUI Application

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Qt and CMake dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake qtbase5-dev qtbase5-dev-tools build-essential cmake
          sudo apt-get install -y libqt5serialport5-dev  # Install Qt5 SerialPort

      # Step 3: Build the Qt project
      - name: Build Qt Project
        run: |
          cd RPS_GUI  # Go to the directory containing CMakeLists.txt
          mkdir -p build
          cd build
          cmake ..
          make
        shell: bash

      # Step 4: Upload binaries (or other artifacts) as artifacts
      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: rps_gui_binaries
          path: RPS_GUI/build/*
